version: '3'

services:
  cassandra:
    networks:
      hostnet: {}
    environment:
      - CASSANDRA_SEEDS=10.0.15.170,10.0.15.171,10.0.15.172
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 3
    image: cassandra

networks:
  hostnet:
    external:
      name: host
